export class Livros {
    creche = [
        {
            titulo1: "O jabuti que sabia de tudo.",
            autor1: " Claudio Fragata.",
            url1: "https://issuu.com/editoraftd/docs/o_jabuti_que_sabia_de_tudo__claudio_fragata",
            imagem1: "../../assets/educacao/livros/0001.jpg",
            tipo1: "creche",
            titulo2: "Mamãe gata e seus pintinhos.",
            autor2: "Claudio Fragata.",
            url2: "https://issuu.com/editoraftd/docs/mama_e_gata_e_seus_pintinhos__cla_udio_fragata",
            imagem2: "../../assets/educacao/livros/0002.jpg",
            tipo2: "creche",
            titulo3: "Tique-taque.",
            autor3: "Flávia Muniz.",
            url3: "https://issuu.com/editoraftd/docs/tique-taque__fla_via_muniz",
            imagem3: "../../assets/educacao/livros/0003.jpg",
            tipo3: "creche",
            titulo4: "Show da natureza.",
            autor4: "Flávia Muniz.",
            url4: "https://issuu.com/editoraftd/docs/show_da_natureza__fla_via_muniz",
            imagem4: "../../assets/educacao/livros/0004.jpg",
            tipo4: "creche",
            titulo5: "O mico-leão.",
            autor5: "Flavio de Souza.",
            url5: "https://issuu.com/editoraftd/docs/o_mico-lea_o__flavio_de_souza",
            imagem5: "../../assets/educacao/livros/0005.jpg",
            tipo5: "creche"

        },
        {
            titulo1: "O pinguim que andou de bonde.",
            autor1: "Monteiro Lobato.",
            url1: "https://issuu.com/editoraftd/docs/o_pinguim_que_andou_de_bonde__monteiro_lobato",
            imagem1: "../../assets/educacao/livros/0006.jpg",
            tipo1: "creche",
            titulo2: "A formiga.",
            autor2: "Flavio de Souza.",
            url2: "https://issuu.com/editoraftd/docs/a_formiga__flavio_de_souza",
            imagem2: "../../assets/educacao/livros/0007.jpg",
            tipo2: "creche",
            titulo3: "Um dia de folga.",
            autor3: "Flávia Muniz.",
            url3: "https://issuu.com/editoraftd/docs/um_dia_de_folga__fla_via_muniz",
            imagem3: "../../assets/educacao/livros/0008.jpg",
            tipo3: "creche",
            titulo4: "O joão-de-barro.",
            autor4: "Flavio de Souza.",
            url4: "https://issuu.com/editoraftd/docs/o_joa_o-de-barro__flavio_de_souza",
            imagem4: "../../assets/educacao/livros/0009.jpg",
            tipo4: "creche",
            titulo5: "O pintinho Sura.",
            autor5: "Monteiro Lobato.",
            url5: "https://issuu.com/editoraftd/docs/o_pintinho_sura__monteiro_lobato",
            imagem5: "../../assets/educacao/livros/0010.jpg",
            tipo5: "creche"
        },
        {
            titulo1: "Pinduca faz um amigo.",
            autor1: "Claudio Fragata.",
            url1: "https://issuu.com/editoraftd/docs/pinduca_faz_um_amigo__claudio_fragata",
            imagem1: "../../assets/educacao/livros/0011.jpg",
            tipo1: "creche",
            titulo2: "",
            autor2: "",
            url2: "",
            imagem2: "",
            tipo2: "",
            titulo3: "",
            autor3: "",
            url3: "",
            imagem3: "",
            tipo3: "",
            titulo4: "",
            autor4: "",
            url4: "",
            imagem4: "",
            tipo4: "",
            titulo5: "",
            autor5: "",
            url5: "",
            imagem5: "",
            tipo5: ""
        },
    ]

    pre = [
        {
            titulo1: "O pinguim que andou de bonde.",
            autor1: "Monteiro Lobato.",
            url1: "https://issuu.com/editoraftd/docs/o_pinguim_que_andou_de_bonde__monteiro_lobato",
            imagem1: "../../assets/educacao/livros/0006.jpg",
            tipo1: "Pré-Escola",
            titulo2: "A formiga.",
            autor2: "Flavio de Souza.",
            url2: "https://issuu.com/editoraftd/docs/a_formiga__flavio_de_souza",
            imagem2: "../../assets/educacao/livros/0007.jpg",
            tipo2: "Pré-Escola",
            titulo3: "Um dia de folga.",
            autor3: "Flávia Muniz.",
            url3: "https://issuu.com/editoraftd/docs/um_dia_de_folga__fla_via_muniz",
            imagem3: "../../assets/educacao/livros/0008.jpg",
            tipo3: "Pré-Escola",
            titulo4: "O joão-de-barro.",
            autor4: "Flavio de Souza.",
            url4: "https://issuu.com/editoraftd/docs/o_joa_o-de-barro__flavio_de_souza",
            imagem4: "../../assets/educacao/livros/0009.jpg",
            tipo4: "Pré-Escola",
            titulo5: "O pintinho Sura.",
            autor5: "Monteiro Lobato.",
            url5: "https://issuu.com/editoraftd/docs/o_pintinho_sura__monteiro_lobato",
            imagem5: "../../assets/educacao/livros/0010.jpg",
            tipo5: "Pré-Escola"
        },
        {
            titulo1: "O jabuti que sabia de tudo.",
            autor1: " Claudio Fragata.",
            url1: "https://issuu.com/editoraftd/docs/o_jabuti_que_sabia_de_tudo__claudio_fragata",
            imagem1: "../../assets/educacao/livros/0001.jpg",
            tipo1: "Pré-Escola",
            titulo2: "Mamãe gata e seus pintinhos.",
            autor2: "Claudio Fragata.",
            url2: "https://issuu.com/editoraftd/docs/mama_e_gata_e_seus_pintinhos__cla_udio_fragata",
            imagem2: "../../assets/educacao/livros/0002.jpg",
            tipo2: "Pré-Escola",
            titulo3: "Tique-taque.",
            autor3: "Flávia Muniz.",
            url3: "https://issuu.com/editoraftd/docs/tique-taque__fla_via_muniz",
            imagem3: "../../assets/educacao/livros/0003.jpg",
            tipo3: "Pré-Escola",
            titulo4: "Show da natureza.",
            autor4: "Flávia Muniz.",
            url4: "https://issuu.com/editoraftd/docs/show_da_natureza__fla_via_muniz",
            imagem4: "../../assets/educacao/livros/0004.jpg",
            tipo4: "Pré-Escola",
            titulo5: "O mico-leão.",
            autor5: "Flavio de Souza.",
            url5: "https://issuu.com/editoraftd/docs/o_mico-lea_o__flavio_de_souza",
            imagem5: "../../assets/educacao/livros/0005.jpg",
            tipo5: "Pré-Escola"

        },
        {
            titulo1: "Pinduca faz um amigo.",
            autor1: "Claudio Fragata.",
            url1: "https://issuu.com/editoraftd/docs/pinduca_faz_um_amigo__claudio_fragata",
            imagem1: "../../assets/educacao/livros/0011.jpg",
            tipo1: "Pré-Escola",
            titulo2: "",
            autor2: "",
            url2: "",
            imagem2: "",
            tipo2: "",
            titulo3: "",
            autor3: "",
            url3: "",
            imagem3: "",
            tipo3: "",
            titulo4: "",
            autor4: "",
            url4: "",
            imagem4: "",
            tipo4: "",
            titulo5: "",
            autor5: "",
            url5: "",
            imagem5: "",
            tipo5: ""
        },
    ]

    

    ano1 = [
        {
            titulo1: "O jabuti que sabia de tudo.",
            autor1: " Claudio Fragata.",
            url1: "https://issuu.com/editoraftd/docs/o_jabuti_que_sabia_de_tudo__claudio_fragata",
            imagem1: "../../assets/educacao/livros/0001.jpg",
            tipo1: "1º ano",
            titulo2: "O pintinho Sura.",
            autor2: "Monteiro Lobato.",
            url2: "https://issuu.com/editoraftd/docs/o_pintinho_sura__monteiro_lobato",
            imagem2: "../../assets/educacao/livros/0010.jpg",
            tipo2: "1º ano",
            titulo3: "O pinguim que andou de bonde.",
            autor3: "Monteiro Lobato.",
            url3: "https://issuu.com/editoraftd/docs/o_pinguim_que_andou_de_bonde__monteiro_lobato",
            imagem3: "../../assets/educacao/livros/0006.jpg",
            tipo3: "1º ano",
            titulo4: "A formiga.",
            autor4: "Flavio de Souza.",
            url4: "https://issuu.com/editoraftd/docs/a_formiga__flavio_de_souza",
            imagem4: "../../assets/educacao/livros/0007.jpg",
            tipo4: "1º ano",
            titulo5: "Caderno de atividades 1º ano.",
            autor5: "Secretaria municipal de Educação.",
            url5: "https://drive.google.com/file/d/1bJlDkheGer2t8VtN8tT2qfPO0LXjRwX8/view",
            imagem5: "../../assets/educacao/livros/0012.jpg",
            tipo5: "1º ano",
        },
        {
            titulo1: "Minha capsula do tempo.",
            autor1: "Secretaria municipal de Maragogipe.",
            url1: "https://drive.google.com/file/d/1CiCDnOWkrHa-2QWCW1h6u1_K4o3rC4VN/view",
            imagem1: "../../assets/educacao/livros/0013.jpg",
            tipo1: "1º ano",
            titulo2: "",
            autor2: "",
            url2: "",
            imagem2: "",
            tipo2: "",
            titulo3: "",
            autor3: "",
            url3: "",
            imagem3: "",
            tipo3: "",
            titulo4: "",
            autor4: "",
            url4: "",
            imagem4: "",
            tipo4: "",
            titulo5: "",
            autor5: "",
            url5: "",
            imagem5: "",
            tipo5: "",
        }
    ]

    ano2 = [
        {
            titulo1: "Narizinho e o príncipe escamado.",
            autor1: "Monteiro Lobato.",
            url1: "https://issuu.com/editoraftd/docs/narizinho_e_o_pri_ncipe_escamado__monteiro_lobato",
            imagem1: "../../assets/educacao/livros/0014.jpg",
            tipo1: "2º ano",
            titulo2: "Festa no céu.",
            autor2: "Ana Maria Machado.",
            url2: "https://issuu.com/editoraftd/docs/festa_no_ce_u__ana_maria_machado",
            imagem2: "../../assets/educacao/livros/0015.jpg",
            tipo2: "2º ano",
            titulo3: "Um nó na cabeça.",
            autor3: "Rosa Amanda Strausz  .",
            url3: "https://issuu.com/editoraftd/docs/um_no__na_cabec_a__rosa_amanda_strausz",
            imagem3: "../../assets/educacao/livros/0016.jpg",
            tipo3: "2º ano",
            titulo4: "Cachinhos de Ouro.",
            autor4: "Ana Maria Machado.",
            url4: "https://issuu.com/editoraftd/docs/cachinhos_de_ouro__ana_maria_machado",
            imagem4: "../../assets/educacao/livros/0017.jpg",
            tipo4: "2º ano",
            titulo5: "Caderno de atividades 2º ano.",
            autor5: "Secretaria municipal de Educação.",
            url5: "https://drive.google.com/file/d/1INWQM5MnwuafDn03xbz7-stLQ61KJeU5/view",
            imagem5: "../../assets/educacao/livros/0018.jpg",
            tipo5: "2º ano",
        },
        {
            titulo1: "Minha capsula do tempo.",
            autor1: "Secretaria municipal de Maragogipe.",
            url1: "https://drive.google.com/file/d/1CiCDnOWkrHa-2QWCW1h6u1_K4o3rC4VN/view",
            imagem1: "../../assets/educacao/livros/0013.jpg",
            tipo1: "1º ano",
            titulo2: "",
            autor2: "",
            url2: "",
            imagem2: "",
            tipo2: "",
            titulo3: "",
            autor3: "",
            url3: "",
            imagem3: "",
            tipo3: "",
            titulo4: "",
            autor4: "",
            url4: "",
            imagem4: "",
            tipo4: "",
            titulo5: "",
            autor5: "",
            url5: "",
            imagem5: "",
            tipo5: "",
        }
    ]

    
    ano3 = [
        {
            titulo4: "Narizinho e o príncipe escamado.",
            autor4: "Monteiro Lobato.",
            url4: "https://issuu.com/editoraftd/docs/narizinho_e_o_pri_ncipe_escamado__monteiro_lobato",
            imagem4: "../../assets/educacao/livros/0014.jpg",
            tipo4: "3º ano",
            titulo3: "Festa no céu.",
            autor3: "Ana Maria Machado.",
            url3: "https://issuu.com/editoraftd/docs/festa_no_ce_u__ana_maria_machado",
            imagem3: "../../assets/educacao/livros/0015.jpg",
            tipo3: "3º ano",
            titulo2: "Um nó na cabeça.",
            autor2: "Rosa Amanda Strausz  .",
            url2: "https://issuu.com/editoraftd/docs/um_no__na_cabec_a__rosa_amanda_strausz",
            imagem2: "../../assets/educacao/livros/0016.jpg",
            tipo2: "3º ano",
            titulo1: "Cachinhos de Ouro.",
            autor1: "Ana Maria Machado.",
            url1: "https://issuu.com/editoraftd/docs/cachinhos_de_ouro__ana_maria_machado",
            imagem1: "../../assets/educacao/livros/0017.jpg",
            tipo1: "3º ano",
            titulo5: "Caderno de atividades 3º ano.",
            autor5: "Secretaria municipal de Educação.",
            url5: "https://drive.google.com/file/d/1LEzau2oN9zyDMoTF8g5lD8KCOMlrkhNU/view",
            imagem5: "../../assets/educacao/livros/0019.jpg",
            tipo5: "3º ano",
        },
        {
            titulo1: "Minha capsula do tempo.",
            autor1: "Secretaria municipal de Maragogipe.",
            url1: "https://drive.google.com/file/d/1CiCDnOWkrHa-2QWCW1h6u1_K4o3rC4VN/view",
            imagem1: "../../assets/educacao/livros/0013.jpg",
            tipo1: "1º ano",
            titulo2: "",
            autor2: "",
            url2: "",
            imagem2: "",
            tipo2: "",
            titulo3: "",
            autor3: "",
            url3: "",
            imagem3: "",
            tipo3: "",
            titulo4: "",
            autor4: "",
            url4: "",
            imagem4: "",
            tipo4: "",
            titulo5: "",
            autor5: "",
            url5: "",
            imagem5: "",
            tipo5: "",
        }
    ]

    
    ano4 = [
        {
            titulo4: "A hidra de Lerxna.",
            autor4: "Monteiro Lobato.",
            url4: "https://issuu.com/editoraftd/docs/a_hidra_de_lerna__monteiro_lobato_-_colec_a_o_os_d",
            imagem4: "../../assets/educacao/livros/0020.jpg",
            tipo4: "4º ano",

            titulo3: "O leão da Nemeia.",
            autor3: "Monteiro Lobato.",
            url3: "https://issuu.com/editoraftd/docs/festa_no_ce_u__ana_maria_machado",
            imagem3: "../../assets/educacao/livros/0022.jpg",
            tipo3: "4º ano",

            titulo2: "Caderno de atividades 4º ano.",
            autor2: "Secretaria munipal de educação.",
            url2: "https://drive.google.com/file/d/1ELx5M9F0IrTHqZGKT4e4ya7mibVEt-OS/view",
            imagem2: "../../assets/educacao/livros/0021.jpg",
            tipo2: "4º ano",

            titulo1: "Minha capsula do tempo.",
            autor1: "Secretaria municipal de Maragogipe.",
            url1: "https://drive.google.com/file/d/1CiCDnOWkrHa-2QWCW1h6u1_K4o3rC4VN/view",
            imagem1: "../../assets/educacao/livros/0013.jpg",
            tipo1: "4º ano",
            
            titulo5: "",
            autor5: "",
            url5: "",
            imagem5: "",
            tipo5: "",
        }
    ]

    
    ano5 = [
        {
            titulo2: "A hidra de Lerxna.",
            autor2: "Monteiro Lobato.",
            url2: "https://issuu.com/editoraftd/docs/a_hidra_de_lerna__monteiro_lobato_-_colec_a_o_os_d",
            imagem2: "../../assets/educacao/livros/0020.jpg",
            tipo2: "5º ano",

            titulo1: "O leão da Nemeia.",
            autor1: "Monteiro Lobato.",
            url1: "https://issuu.com/editoraftd/docs/festa_no_ce_u__ana_maria_machado",
            imagem1: "../../assets/educacao/livros/0022.jpg",
            tipo1: "5º ano",

            titulo4: "Caderno de atividades 5º ano.",
            autor4: "Secretaria munipal de educação.",
            url4: "https://drive.google.com/file/d/1N6OVrw_UgalS9EwV071zLyUad773cZWL/view",
            imagem4: "../../assets/educacao/livros/0023.jpg",
            tipo4: "5º ano",

            titulo3: "Minha capsula do tempo.",
            autor3: "Secretaria municipal de Maragogipe.",
            url3: "https://drive.google.com/file/d/1CiCDnOWkrHa-2QWCW1h6u1_K4o3rC4VN/view",
            imagem3: "../../assets/educacao/livros/0013.jpg",
            tipo3: "5º ano",
            
            titulo5: "",
            autor5: "",
            url5: "",
            imagem5: "",
            tipo5: "",
        }
    ]

    
    ano6 = [
        {
            titulo2: "Sherlock Holmes_ Casos Extraordinários.",
            autor2: "Arthur Conan Doyle.",
            url2: "https://issuu.com/editoraftd/docs/sherlock_holmes__casos_extraordina_rios__arthur_co",
            imagem2: "../../assets/educacao/livros/0024.jpg",
            tipo2: "6º ano",
            titulo1: "A reforma da natureza.",
            autor1: "Monteiro Lobato.",
            url1: "https://issuu.com/editoraftd/docs/a_reforma_da_natureza__monteiro_lobato",
            imagem1: "../../assets/educacao/livros/0025.jpg",
            tipo1: "6º ano",
            titulo4: "A ilha do tesouro.",
            autor4: "Robert Louis Stevenson.",
            url4: "https://issuu.com/editoraftd/docs/a_ilha_do_tesouro__robert_louis_stevenson",
            imagem4: "../../assets/educacao/livros/0023.jpg",
            tipo4: "6º ano",
            titulo3: "Minha capsula do tempo.",
            autor3: "Secretaria municipal de Maragogipe.",
            url3: "https://drive.google.com/file/d/1CiCDnOWkrHa-2QWCW1h6u1_K4o3rC4VN/view",
            imagem3: "../../assets/educacao/livros/0013.jpg",
            tipo3: "6º ano",
            titulo5: "Caderno de atividade 6º ano",
            autor5: "Secretaria municipal de educação",
            url5: "https://drive.google.com/file/d/1M5gy7f5Lv1ARO77A4YJMuLnv57jPP4Iy/view",
            imagem5: "../../assets/educacao/livros/0026.jpg",
            tipo5: "6º ano",
        }
    ]

    
    ano7 = [
        {
            titulo1: "Sherlock Holmes_ Casos Extraordinários.",
            autor1: "Arthur Conan Doyle.",
            url1: "https://issuu.com/editoraftd/docs/sherlock_holmes__casos_extraordina_rios__arthur_co",
            imagem1: "../../assets/educacao/livros/0024.jpg",
            tipo5: "7º ano",
            titulo5: "A reforma da natureza.",
            autor5: "Monteiro Lobato.",
            url5: "https://issuu.com/editoraftd/docs/a_reforma_da_natureza__monteiro_lobato",
            imagem5: "../../assets/educacao/livros/0025.jpg",
            tipo1: "7º ano",
            titulo3: "A ilha do tesouro.",
            autor3: "Robert Louis Stevenson.",
            url3: "https://issuu.com/editoraftd/docs/a_ilha_do_tesouro__robert_louis_stevenson",
            imagem3: "../../assets/educacao/livros/0023.jpg",
            tipo3: "7º ano",
            titulo4: "Minha capsula do tempo.",
            autor4: "Secretaria municipal de Maragogipe.",
            url4: "https://drive.google.com/file/d/1CiCDnOWkrHa-2QWCW1h6u1_K4o3rC4VN/view",
            imagem4: "../../assets/educacao/livros/0013.jpg",
            tipo4: "7º ano",
            titulo2: "Caderno de atividade 7º ano",
            autor2: "Secretaria municipal de educação",
            url2: "https://drive.google.com/file/d/1SxG6seQGERaH44smhlFaf6teJCWA_2QC/view",
            imagem2: "../../assets/educacao/livros/0027.jpg",
            tipo2: "7º ano",
        }
    ]

    
    ano8 = [
        {
            titulo1: "Canino branco.",
            autor1: "Jack London.",
            url1: "https://issuu.com/editoraftd/docs/canino_branco__de_jack_london",
            imagem1: "../../assets/educacao/livros/0028.jpg",
            tipo1: "8º ano",
            tipo5: "8º ano",
            titulo5: "Robinson Crusoé.",
            autor5: "Daniel Defoe.",
            url5: "https://issuu.com/editoraftd/docs/robinson_crusoe___daniel_defoe",
            imagem5: "../../assets/educacao/livros/0029.jpg",
            titulo3: "Frankenstein.",
            autor3: "Mary Shelley.",
            url3: "https://issuu.com/editoraftd/docs/frankenstein__de_mary_shelley",
            imagem3: "../../assets/educacao/livros/0030.jpg",
            tipo3: "8º ano",
            titulo2: "Minha capsula do tempo.",
            autor2: "Secretaria municipal de Maragogipe.",
            url2: "https://drive.google.com/file/d/1CiCDnOWkrHa-2QWCW1h6u1_K4o3rC4VN/view",
            imagem2: "../../assets/educacao/livros/0013.jpg",
            tipo2: "8º ano",
            titulo4: "Caderno de atividade 8º ano",
            autor4: "Secretaria municipal de educação",
            url4: "https://drive.google.com/file/d/1qWzKevxibeCn2aPxz564eoQzG7ioCXm3/view",
            imagem4: "../../assets/educacao/livros/0033.jpg",
            tipo4: "8º ano",
        }
    ]

    
    ano9 = [
        {
            titulo4: "Canino branco.",
            autor4: "Jack London.",
            url4: "https://issuu.com/editoraftd/docs/canino_branco__de_jack_london",
            imagem4: "../../assets/educacao/livros/0028.jpg",
            tipo4: "9º ano",
            tipo2: "9º ano",
            titulo2: "Robinson Crusoé.",
            autor2: "Daniel Defoe.",
            url2: "https://issuu.com/editoraftd/docs/robinson_crusoe___daniel_defoe",
            imagem2: "../../assets/educacao/livros/0029.jpg",
            titulo3: "Frankenstein.",
            autor3: "Mary Shelley.",
            url3: "https://issuu.com/editoraftd/docs/frankenstein__de_mary_shelley",
            imagem3: "../../assets/educacao/livros/0030.jpg",
            tipo3: "9º ano",
            titulo5: "Minha capsula do tempo.",
            autor5: "Secretaria municipal de Maragogipe.",
            url5: "https://drive.google.com/file/d/1CiCDnOWkrHa-2QWCW1h6u1_K4o3rC4VN/view",
            imagem5: "../../assets/educacao/livros/0013.jpg",
            tipo5: "9º ano",
            titulo1: "Caderno de atividade 9º ano",
            autor1: "Secretaria municipal de educação",
            url1: "https://drive.google.com/file/d/1Hljxw_dipMOBhOQtQvTS4WSYO0H7Gc8C/view",
            imagem1: "../../assets/educacao/livros/0031.jpg",
            tipo1: "9º ano",
        }
    ]

    EJA1 = [
        {
            titulo4: "",
            autor4: "",
            url4: "",
            imagem4: "",
            tipo4: "",
            tipo5: "",
            titulo5: "",
            autor5: "",
            url5: "",
            imagem5: "",
            titulo3: "",
            autor3: "",
            url3: "",
            imagem3: "",
            tipo3: "",
            titulo2: "Minha capsula do tempo.",
            autor2: "Secretaria municipal de Maragogipe.",
            url2: "https://drive.google.com/file/d/1CiCDnOWkrHa-2QWCW1h6u1_K4o3rC4VN/view",
            imagem2: "../../assets/educacao/livros/0013.jpg",
            tipo2: "EJA",
            titulo1: "Caderno de atividade 5º / 6º Serie",
            autor1: "Secretaria municipal de educação",
            url1: "https://drive.google.com/file/d/1dGplSI8H_Kb0FEMwrE3-JhQvNhyAEpzk/view",
            imagem1: "../../assets/educacao/livros/0032.jpg",
            tipo1: "EJA1",
        }
    ]
    
    EJA2 = [
        {
            titulo4: "",
            autor4: "",
            url4: "",
            imagem4: "",
            tipo4: "",
            tipo5: "",
            titulo5: "",
            autor5: "",
            url5: "",
            imagem5: "",
            titulo3: "",
            autor3: "",
            url3: "",
            imagem3: "",
            tipo3: "",
            titulo2: "Minha capsula do tempo.",
            autor2: "Secretaria municipal de Maragogipe.",
            url2: "https://drive.google.com/file/d/1CiCDnOWkrHa-2QWCW1h6u1_K4o3rC4VN/view",
            imagem2: "../../assets/educacao/livros/0013.jpg",
            tipo2: "EJA",
            titulo1: "Caderno de atividade 7º / 8º Serie",
            autor1: "Secretaria municipal de educação",
            url1: "https://drive.google.com/file/d/1qajXT0s_32SgiEQhnkeGfmaMoXY1h8Ex/view",
            imagem1: "../../assets/educacao/livros/0034.jpg",
            tipo1: "EJA2",
        }
    ]

    
    AEE = [
        {
            titulo4: "",
            autor4: "",
            url4: "",
            imagem4: "",
            tipo4: "",
            tipo5: "",
            titulo5: "",
            autor5: "",
            url5: "",
            imagem5: "",
            titulo3: "",
            autor3: "",
            url3: "",
            imagem3: "",
            tipo3: "",
            titulo2: "",
            autor2: "",
            url2: "",
            imagem2: "",
            tipo2: "",
            titulo1: "AEE",
            autor1: "Secretaria municipal de educação",
            url1: "https://drive.google.com/file/d/1etB2H2Yp2XdRPY_mNaS6W6XU1-IjWU1U/view",
            imagem1: "../../assets/educacao/livros/0035.jpg",
            tipo1: "EJA2",
        }
    ]
}
